#!/bin/sh
#DEBHELPER#

if [ -z "$2" ]; then
	systemctl enable ssh
	systemctl disable kplex
	systemctl disable pypilot@pypilot.service
	systemctl disable pypilot_web
	systemctl mask pypilot_web
	systemctl enable signalk
	systemctl disable vnc
	systemctl mask vnc
	systemctl disable mopidy
	mkdir -p /home/user/.local/share/applications
	chown 1000:1000  /home/user/.local/share/applications
	cp /usr/local/share/applications/pypilot_calibration.desktop /home/user/.local/share/applications/pypilot_calibration.desktop
	cp /usr/local/share/applications/pypilot_webapp.desktop /home/user/.local/share/applications/pypilot_webapp.desktop
	 cp /usr/local/share/applications/signalk.desktop /home/user/.local/share/applications/signalk.desktop
	echo "Hidden=true" >> /home/user/.local/share/applications/musicbox.desktop
	echo "Hidden=true" >> /home/user/.local/share/applications/pypilot_webapp.desktop
	echo "Hidden=true" >> /home/user/.local/share/applications/pypilot_calibration.desktop
	chown 1000:1000 /home/user/.local/share/applications/musicbox.desktop
	chown 1000:1000 /home/user/.local/share/applications/pypilot_webapp.desktop
	chown 1000:1000 /home/user/.local/share/applications/pypilot_calibration.desktop
	echo "First install setup done."
fi


exit 0